### ISSUE TITLE
RuntimeError: Error building extension 'rcca'

### ISSUE THREAD

**Issue by immortal13** [ShaneShen/ENL-FCN#1]
Thanks for your code! Could you please tell me how to solve the problem: "RuntimeError: Error building extension 'rcca'" ?

**Comment by ShaneShen** [comment]
Hi, I did not find this problem. Maybe you can check the CCNet https://github.com/speedinghzl/CCNet/tree/pytorch-1.1. Some C related codes are required.

**Comment by YichuXu** [comment]
@immortal13  i meet the same problem as u

**Comment by ZJunBo** [comment]
原因是因为CUDA版本不对 ENL也是参考CCNet ，rcca是用cuda编写的代码 CUDA版本为10.1应该没问题，我显卡为3060 cuda11系列，解决办法是把CCattention部分的代码用纯python替换
