### ISSUE TITLE
抄袭？

### ISSUE THREAD

**Issue by jinyuwei** [ShaneShen/ENL-FCN#2]
赤裸裸地抄袭CCNet，能不能有点学术道德

**Comment by ShaneShen** [comment]
In Introdution and Related Methods, we clearly stated that CCNet is used in this paper and CCNet is cited several times. 
We believe that it is a good way to apply CCNet in more fileds, including RS image analysis.
谢谢你提出的质疑。我们在文中明确说明了方法是来自CCNet并且也多次引用了CCNet. 我们觉得把CCNet应用到更多领域，尤其是计算量大的HSI中是一种值得尝试的方法。希望有更多交流

**Comment by jinyuwei** [comment]
已收到！谢谢                金宇伟  Yuwei Jin Ph.D of Remote Sensing  Information Science and technology of UESTC2006 Xiyuan Road, Gaoxin Western District, Chengdu, Sichuan, P. R. ***@***.***;
